### ISSUE TITLE
having a Authentication issue

### ISSUE THREAD

**Issue by markod21uk** [EvanBasalik/OOFSponder#26]
![2021-02-15 15_11_13-Window](https://user-images.githubusercontent.com/31213829/107965457-7435cc80-6fa2-11eb-9044-bb81c2619258.png)

**Comment by EvanBasalik** [comment]
The production build is still locked to the Microsoft tenant. Please try the Insider build (https://oofsponderdeploy.blob.core.windows.net/insider/install.htm). You should get an Admin Consent required message and if you get an admin to consent, you should be able to use it in your tenant.

**Comment by srussell-1** [comment]
Hi Evan, thanks for your help. I have installed the Insider Build and I am still getting the same error message.

![OOFSponder Error](https://user-images.githubusercontent.com/79135164/108034322-4053b900-702d-11eb-9eca-6a793ffc52e8.PNG)

**Comment by EvanBasalik** [comment]
apologies - just realized that I didn't actually push the updates to Insider. Just pushed them and you should get an update the next time you run OOFSponder
