### ISSUE TITLE
application wont start

### ISSUE THREAD

**Issue by abarqawi** [EvanBasalik/OOFSponder#32]
i was using this application since long time
suddenly stopped working , doubleclick shows only downloading app from click once 

tried uninstall/install didnt help 
no logs found in EventVeiwer 
any suggestions 

![image](https://user-images.githubusercontent.com/16225699/114716638-e9bcdf80-9d3c-11eb-9663-3d6b50e19ff1.png)

**Comment by j0bb0** [comment]
> i was using this application since long time suddenly stopped working , doubleclick shows only downloading app from click once
> 
> tried uninstall/install didnt help no logs found in EventVeiwer any suggestions
> 
> ![image](https://user-images.githubusercontent.com/16225699/114716638-e9bcdf80-9d3c-11eb-9663-3d6b50e19ff1.png)

I met same issue just like you
