### ISSUE TITLE
OOFSponder interrupts my work

### ISSUE THREAD

**Issue by coraphise** [EvanBasalik/OOFSponder#34]
Having re-read how OOFSponder works, I think the "check every 10 minutes" is triggering OOFSponder to pop up on my screen briefly, then hide again. This will sometimes interrupt me clicking on something, or can affect my typing by not only interrupting what I'm typing, but setting my cursor back a character. When focus resumes I can get some interesting results.

Is there a way I can get OOFSponder to keep doing its check without popping up in the foreground?

**Comment by EvanBasalik** [comment]
@coraphise this has been addressed in the new Insider build. It should be pushed to the Production release in the next week or so, but feel free to test Insider in the meantime.
