### ISSUE TITLE
OOFSponder no longer works

### ISSUE THREAD

**Issue by jdsixtos** [EvanBasalik/OOFSponder#36]
OOFSponder was working fine for years and one day just stopped working. Is this tool still maintained? It shows that I'm using my @microsoft.com account, but it no longer sets up my OOF message in Outlook/Exchange.

**Comment by cbattlegear** [comment]
Currently it is in a holding pattern and not actively maintained beyond some fixed @EvanBasalik drops in for security items. We've both moved out of support for several years and haven't had a chance to dedicate time to the project. 

More than happy to bring in other maintainers if anyone would be willing to help, to be honest at this point we could probably just turn this into a simple PowerApp also as they didn't exist when this was first built nearly 8 years ago.

**Comment by coraphise** [comment]
My "fix", that I'm not sure will hold...

Search under your AppData folder for OOFSponder
I had two shortcuts come up, try both; if one launches, copy that shortcut to wherever you normally launch from
