### ISSUE TITLE
Save button is hidden under taskbar

### ISSUE THREAD

**Issue by mustafawad** [EvanBasalik/OOFSponder#45]
The save button is hidden under taskbar, we have to autohide the taskbar to view the save button! I am using Windows 11.

![Screenshot 2024-04-15 224952](https://github.com/EvanBasalik/OOFSponder/assets/40309881/81d7ec5d-918c-4520-b0a9-ed8aaafbbbad)

**Comment by EvanBasalik** [comment]
This is usually because the window for some reason resizes such that it is off the screen and Windows is helpfully preserving that layout. You can normally use the right-click -> Move trick to get it back on-screen so you can fix the size.

**Comment by EvanBasalik** [comment]
As part of moving to .NET Standard, was able to do some UI fixes that will address this. It will be fixed in 3.0
