### ISSUE TITLE
Saved OOF Messages Disappeared after Updating OOFSponder

### ISSUE THREAD

**Issue by kalinzange** [EvanBasalik/OOFSponder#49]
Hi,

Pretty much the title says everything, after updating this week, both my internal and external messages became blank. It was working before I got on vacations (June 7th). Is there anyway to recover the past OOF Messages? since for external I'm unable to retrieve the message.

**Comment by EvanBasalik** [comment]
Sorry - this was an unfortunate side effect of having to move the install location between Storage accounts. You shouldn't see this happen again.
