### ISSUE TITLE
Email message disappears after Update

### ISSUE THREAD

**Issue by frcardos** [EvanBasalik/OOFSponder#59]
I wanted to share some feedback regarding the application. 
One thing I found challenging was losing the messages in both options and having to rewrite everything from scratch after an update.

Would it be possible to implement a feature that keeps a hidden file with the email messages, for example in the same folder as the application or in the windows registry if possible?
This way, if we update the application, it could automatically retrieve and fill in the information.

Thank you for considering this suggestion. I believe it would greatly enhance the user experience.

**Comment by EvanBasalik** [comment]
Added automatic periodic saving plus the ability to load an existing HTML file in v3.0. 

Unfortunately, no way to backport to 2.5.x without a ton of work, so am going to do my best to make sure that the upgrade from 2.5 --> 3.0 doesn't lose the existing message and then going forward it will have the saves.
