### ISSUE TITLE
Add a Help Menu Tool bar with some options

### ISSUE THREAD

**Issue by frcardos** [EvanBasalik/OOFSponder#60]
I wanted to share some feedback regarding the application. 
Have you thought about adding a Help Menu to the Tool Bar?
In this Help button you can add options like,

About OFFSponder -> were we check the current version and have a link to your Application Mainp Page
Help -> a link to the Help Page of the OFFSponder
Check Updates -> where we could check for any latest update and do it with a click.

Thank you for considering this suggestion. I believe it would greatly enhance the user experience.

**Comment by EvanBasalik** [comment]
Added About box with the above. Feedback welcome.

#82
